# -*- coding: utf-8 -*-
"""Resume screener task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaUIRsvFbSR9eDrjUUsZNX8D_dpOunEo
"""

!pip install -r requirements.txt

import os
os.makedirs("my_resumes", exist_ok=True)

print(os.listdir("my_resumes"))

!python resume_screener.py --jd my_resumes/job_description.txt --resumes my_resumes --output results.csv

import pandas as pd
pd.read_csv("results.csv")

